### PR TITLE
Fixed a typo in README.md

### PR DESCRIPTION
**Pull request by UltimateMcraft**
Details was somehow Detals...

### CODE REVIEW

**Comment by PEMapModder** [comment]
Why am I added?

**Comment by AndreTheGamer** [comment]
Same, i was added without any prior permission from me..

**Comment by UltimateMcraft** [comment]
Who owns this repo?

**Comment by PEMapModder** [comment]
Wait, you are making pull requests here without knowing the background?

**Comment by UltimateMcraft** [comment]
I fixed a typo.

**Comment by PEMapModder** [comment]
@AndreTheGamer created this repo. I will remove myself, and will block @AndreTheGamer from my account.

**Comment by flaxues** [comment]
@PEMapModder MateiGamingYTB maded created this repo

**Comment by UltimateMcraft** [comment]
This repo appeared on my home page, it says MateiGamingYTB created it.

**Comment by flaxues** [comment]
https://github.com/MateiGamingYTB?tab=activity

**Comment by PEMapModder** [comment]
But @AndreTheGamer pushed most of the commits?

**Comment by PEMapModder** [comment]
Oops, my wrong

**Comment by UltimateMcraft** [comment]
MateiGamingYTB added MrDoni98 to ILOVEMCPE/PocketMine-MP
16 hours ago
MateiGamingYTB added minecraftgenius76 to ILOVEMCPE/PocketMine-MP
16 hours ago
MateiGamingYTB added luca28pet to ILOVEMCPE/PocketMine-MP
16 hours ago
MateiGamingYTB added EmreTr1 to ILOVEMCPE/PocketMine-MP
16 hours ago
MateiGamingYTB added PEMapModder to ILOVEMCPE/PocketMine-MP
16 hours ago
MateiGamingYTB added flaxues to ILOVEMCPE/PocketMine-MP
16 hours ago
MateiGamingYTB added Driesboy to ILOVEMCPE/PocketMine-MP
17 hours ago
MateiGamingYTB added TheKillerTacos to ILOVEMCPE/PocketMine-MP
17 hours ago
MateiGamingYTB added shoghicp to ILOVEMCPE/PocketMine-MP
17 hours ago
MateiGamingYTB added keithkfng to ILOVEMCPE/PocketMine-MP
17 hours ago
MateiGamingYTB added AndreTheGamer to ILOVEMCPE/PocketMine-MP
17 hours ago

**Pull request merged**
